### ISSUE TITLE
Minecraft.paused should be Minecraft.appletMode in beta 1.7.3

### ISSUE THREAD

**Issue by Niterux** [OrnitheMC/feather-mappings#152]
**Type**  
Field

**Describe where the element is**  
Lnet/minecraft/client/Minecraft;paused:Z

**Description of the element**  
Stores whether the game is running in an applet

**Expected name**  
appletMode

**Additional Context**
It is unknown to me how this mapping affects other versions

**Comment by SpaceWalkerRS** [comment]
thanks - it's possible this affects versions as far as 1.5.2 (the last version to use applets)

**Comment by SpaceWalkerRS** [comment]
fixed in 3bddacc
