### ISSUE TITLE
getDamageTracker Should be getMovementControl

### ISSUE THREAD

**Issue by calmilamsy** [OrnitheMC/feather-mappings#165]
**Minecraft Version**
Pretty sure this is relevant from r1.2 up until r1.14. Found on r1.2.

**Type**  
Method

**Info**
See `MobEntity:getDamageTracker`, it returns `movementControl`.  
All method calls indicate to this actually being movement control, as it's updated by `PathNavigation:tick`, so it's thankfully a single method fix and not the other way around.

**Comment by SpaceWalkerRS** [comment]
It appears to only affect versions up to 1.5.2, in 13w16a and above `getDamageTracker` is the correct name. I'll push a fix, thanks for the report!
