### ISSUE TITLE
Update style guide and update mappings to match it

### ISSUE THREAD

**Issue by SpaceWalkerRS** [OrnitheMC/feather-mappings#37]
We have had some discussions on Discord about naming and style conventions, and the numerous inconsistencies in the current mappings. The style guide should be updated to include the things we discussed and then the mappings should be updated to make sure it follows these guidelines correctly.

Suggested changes/additions:
- **Handling of anonymous classes** - before 1.8.2-pre5 anonymous and inner classes were stripped from their parent class. These classes should be treated as any other regular class in terms of naming and packaging, but a note should be included in the java docs to state that it is an anonymous class and link to its parent class.
- Use `random`, not `rand`.
- Use `world`, not `level`.
- Use `parentBlockEntity` for block entities owned by screens.
- Use `client` for `MinecraftClient` fields.
- Use `connection` for `ClientConnection` fields
- Use `TEXTURE` for static final `Identifier` fields which store the main/default texture used for a model/screen/similar thing.
- Use `<PREFIX>_TEXTURE` for static final `Identifier` fields which store non-default/-main textures or textures which would not make sense to name with the above convention (for example `INVULNERABLE_TEXTURE` in `WitherEntityRenderer` or `SHADOW_TEXTURE` in `EntityRenderer`).
- Use `MODEL` for static final `Model` fields which store the main/default model of a class.
- Use `<PREFIX>_MODEL` for static final Model fields which store extra/alternative models for a class, or for all models in a class where there is no clear "main" model.
- Do not use the `Abstract` prefix when naming abstract classes if possible.
- Use `dir` for `Direction` objects (1.8+) or ints representing any of the six possible directions.
  - Use `face` when referring to a specific side of a block.
- Use `facing` for ints representing cardinal directions.
- When a class contains a single instance of itself as a static field, name it `INSTANCE` (all capitalized, even if the field is not final).
- For NBT related methods:
  - Use `toNbt` for non static methods that convert the object to NBT.
  - Use `fromNbt` for static methods that take in NBT and create an object from it.
  - Use `writeNbt` for non static methods that take in NBT and write data to it.
  - Use `readNbt` for non static methods that take in NBT and read data from it.
- Use `buffer` for `ByteBuf` and `PacketByteBuf` parameters.
- Use `font` for `TextRenderer` fields/parameters.

Feel free to suggest other changes or additions in the comments and I will keep this post updated with the changes we agree upon.

**Comment by KayleighWasTaken** [comment]
We should agree on some standard for what to do in the cases where `LOGGER` cannot be used for the logger due to conflicts from inheritance etc. I used `lOGGER` when I went through and did all the loggers since that was already in the mappings somewhere, but there is probably a better way.

**Comment by KayleighWasTaken** [comment]
A few things I've been doing off the top of my head
- `parentBlockEntity` for block entities owned by screens.
- `client` for `MinecraftClient` fields
- `connection` for `ClientConnection` fields
- `TEXTURE` for `static final Identifier` fields which store the main/default texture used for a model/screen/similar thing
- `PREFIX_TEXTURE` for `static final Identifier` fields which store an non-default/main textures or textures which would not make sense to name with the above convention (for example `INVULNERABLE_TEXTURE` in `WitherEntityRenderer` or `SHADOW_TEXTURE` in `EntityRenderer`)
- `MODEL` for `static final Model` fields which store the main/default model of a class.
- `PREFIX_MODEL` for `static final Model` fields which store extra/alternative models for a class, or for all models in a class where there is no clear "main" model.

**Comment by KayleighWasTaken** [comment]
`proxy` for `Proxy` and related fields.

**Comment by viktor40** [comment]
> We should agree on some standard for what to do in the cases where `LOGGER` cannot be used for the logger due to conflicts from inheritance etc. I used `lOGGER` when I went through and did all the loggers since that was already in the mappings somewhere, but there is probably a better way.

This is no longer necessary. The latest enigma version supports shadowing `Static` fields
