### ISSUE TITLE
Update contributing guidlines

### ISSUE THREAD

**Issue by SpaceWalkerRS** [OrnitheMC/feather-mappings#38]
As we are not using the so-called "cleanroom policy" that Yarn is, the contributing guidelines should be updated to reflect that.

**Comment by KayleighWasTaken** [comment]
Should still have a note in my opinion that says at the very least you still shouldn't duplicate other projects mappings unless its trivial stuff.

**Comment by SpaceWalkerRS** [comment]
I think in practice the only line that needs changing is 
```
This includes using the names from those mappings for inspiration.
```
It could be removed but it might be better to explicitly state that using them for inspiration is allowed.

**Comment by Copetan** [comment]
branch was merged
