### ISSUE TITLE
Github Organization

### ISSUE THREAD

**Issue by Copetan** [OrnitheMC/feather-mappings#43]
Some people have brought up the topic of making a Github organization to better organize all the repositories associated with the Ornithe project, but there are a couple things that have to be ironed out at the time repository transfer occurs in order to reduce any possible issues that could arise from this, and I'd want to hear some opinions from others that have contributed to the project.

Current repositories would likely be moved to the organization would be:
- This repository, [feather-mappings](https://github.com/Copetan/feather-mappings)
- [The intermediary repository](https://github.com/Copetan/Intermediary)
- [The 1.7.2 example mod repository](https://github.com/Copetan/1.7.2-fabric-example-mod)
- @viktor40's [FeatherScripts repository](https://github.com/viktor40/FeatherScripts)
- _Maybe_ Vik's [fork of Enigma](https://github.com/viktor40/Enigma), but ideally this would be an "unforked" repository

After repositories are moved, we have to make sure any forks referencing this repository don't somehow break, and that git remote references to this repository are changed accordingly, and to remember to change [the link pointing to the Intermediary repository](https://github.com/Copetan/feather-mappings/blob/3b99f234a2adc11f279918fe9a48d3513a882703/build.gradle#L210).

**Comment by Copetan** [comment]
Some other things we have to consider:
- What should the name of the organization be? Ornithe? OrnitheMC? OrnitheProject?
- If we ever consider making a website, what would it be called? What TLD should we use? How would it be funded? Even if we decide on not making a website, the potential name we would choose is relevant to the next point.
- Currently, artifacts for Feather mappings and Ornithe-Intermediary mappings are stored [in an Artifactory Maven repository hosted by JFrog, registered under my account](https://copetan.jfrog.io/artifactory/minecraft-maven/), under the `me.copetan` package. Should these artifacts be transferred to a new Maven repository server? Should the artifacts be moved to another package (named after the website name and TLD we chose for the previous point)?

**Comment by viktor40** [comment]
My feather scripts repository can be moved to the organization. I agree that my enigma fork should not be moved. It is best to either create a new fork or create an unforked repository. My enigma fork was just for some testing purposes and has nothing important on it.

Some notes regarding your questions.
- I prefer OrinthMC personally.
- i think for a website we can could probably use a github pages website at the moment. Funding won't be necessary and such a website is easy to make and easy to change. A github org can have its own page..
- I prefer `.net` as a TLD
- as a domain name i would use `organisation.net`, since i like OrintheMC the website would be `orinthmc.net`
- I don't know anything about maven stuff so i cannot comment on that.

**Comment by SpaceWalkerRS** [comment]
- My vote would go to "Ornithe", with "OrnitheMC" a close second.
- I agree with Viktor here, a GitHub pages website is fine for now.
- Again, I agree with Viktor, I would go with `<organization>.net`.
- Yes and yes.

**Comment by MaheEvil** [comment]
- OrnitheMC or OrnitrProject would get my vote.
- I also agree here, a GH pages website should be enough

I don't really see a issue with the maven repo staying as is, but I'd be fine with anything.
for other things I agree with vik.

**Comment by thdaele** [comment]
- I think OrnitheMC is best, 
- I agree with using github pages for now 
- yes to both questions.

**Comment by Copetan** [comment]
The relevant repositories have been moved, but I'm going to keep this issue open until we've moved the Maven repository over to another place

**Comment by thdaele** [comment]
> The relevant repositories have been moved, but I'm going to keep this issue open until we've moved the Maven repository over to another place

I think that is done too so we should be able to close this issue?

**Comment by SpaceWalkerRS** [comment]
now that everything is on the new maven I think this issue can be closed?
